# Generated by Django 4.2.5 on 2023-09-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="id",
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
