# Generated by Django 4.2.5 on 2023-09-25 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TestApp", "0002_remove_lesson_id_lesson_lesson_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="lessons",
            field=models.ManyToManyField(through="TestApp.View", to="TestApp.lesson"),
        ),
        migrations.AddField(
            model_name="view",
            name="lesson",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="TestApp.lesson",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="view",
            name="user",
            field=models.ForeignKey(
                default=11,
                on_delete=django.db.models.deletion.CASCADE,
                to="TestApp.user",
            ),
            preserve_default=False,
        ),
    ]
